<?php $_invoice = $block->getInvoice() ?>
<?php $_order = $block->getOrder() ?>
<?php
$isBarcode = $block->getItemBarcode();
$pageSize = $block->getPageSize();
$a4Barcode = $isBarcode && ($pageSize === 'A4');
$a5Barcode = $isBarcode && ($pageSize === 'A5');

$_store = $_order->getStore();
$_imageHelper = $block->getHelperImage();
$_baseImageUrl = $_store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product';

if ($pageSize === 'A7' || $pageSize === 'A6') {
    ?>
    <style>
        .mp-invoice-barcode {
            display: none;
        }
    </style>
<?php } ?>
<?php if ($_invoice && $_order): ?>
    <div class="table">
        <div class="mp-row mp-heading">
            <div class="<?= /** @noEscape */
            $a4Barcode ? 'mp-image-bc' : 'mp-image' ?>">
                <span><?= /* @noEscape */
                    __('Image') ?><span>
            </div>
            <div class="<?= /** @noEscape */
            $a4Barcode ? 'mp-item-bc' : 'mp-item' ?>">
                <span><?= /* @noEscape */
                    __('Items') ?><span>
            </div>
            <?php if ($a4Barcode): ?>
                <div class="mp-barcode-bc">
                    <span></span>
                </div>
            <?php endif ?>
            <div class="<?= /** @noEscape */
            $a4Barcode ? 'mp-qty-bc' : 'mp-qty' ?>">
                <span> <?= /* @noEscape */
                    __('Qty') ?></span>
            </div>
            <div class="<?= /** @noEscape */
            $a4Barcode ? 'mp-price-bc' : 'mp-price' ?>">
                <span><?= /* @noEscape */
                    __('Price') ?></span>
            </div>
            <div class="<?= /** @noEscape */
            $a4Barcode ? 'mp-subtotal-bc' : 'mp-subtotal' ?>">
                <span><?= /* @noEscape */
                    __('Subtotal') ?></span>
            </div>
        </div>
        <?php $i = 0 ?>
        <?php foreach ($_invoice->getAllItems() as $_item): ?>
            <?php
            $block->setItem($_item);
            $indexKey = $i % 2 == 0 ? "odd" : "even";
            if ($block->isBundleItem()) {
                echo $block->renderBundleItem($_item, $_order, $block->getInvoiceType(), $indexKey, $isBarcode, 'bundleitemswimg.phtml');
                $i++;
                continue;
            }

            if ($_item->getOrderItem()->getParentItem()) {
                continue;
            }
            $i++;
            ?>
            <div class="mp-row <?= /** @noEscape */
            $indexKey ?>" style="border-bottom: 1px solid #ddd;">
                <div class="<?= /** @noEscape */
                $a4Barcode ? 'mp-image-bc' : 'mp-image' ?>">
                    <img src="<?= $_imageHelper->init($_item->getOrderItem()->getProduct(), 'small_image',
                        ['type' => 'small_image'])->keepAspectRatio(true)->resize('65', '65')->getUrl(); ?>"
                         alt="<?= __('Product Image'); ?>">
                </div>
                <div class="<?= /** @noEscape */
                $a4Barcode ? 'mp-item-bc' : 'mp-item' ?>">
                    <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                    <p class="sku"><?= /* @noEscape */
                        __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
                    <?php if ($block->getItemOptions()): ?>
                        <p>
                            <?php $c = 0 ?>
                            <?php foreach ($block->getItemOptions() as $option): ?>
                                <strong><em><?= /* @noEscape */
                                    $option['label'] ?>: </em></strong><?= /* @noEscape */
                                nl2br($option['value']) ?>
                                <?php ++$c;
                                if ($c < count($block->getItemOptions())) {
                                    echo '; ';
                                } ?>
                            <?php endforeach ?>
                        </p>
                    <?php endif ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock() ?>
                    <?php if ($addInfoBlock) : ?>
                        <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
                    <?php endif ?>
                    <?= $block->escapeHtml($_item->getDescription()) ?>
                    <?php if ($a5Barcode): ?>
                        <p>
                            <barcode code="<?= $block->escapeHtml($block->getSku($_item)) ?>" type="C39E" size="0.9"
                                     height="0.7"/>
                        </p>
                    <?php endif ?>
                </div>
                <?php if ($a4Barcode): ?>
                    <div class="mp-barcode-bc">
                        <p>
                            <barcode code="<?= $block->escapeHtml($block->getSku($_item)) ?>" type="C39E" size="0.6"/>
                        </p>
                    </div>
                <?php endif ?>
                <div class="<?= /** @noEscape */
                $a4Barcode ? 'mp-qty-bc' : 'mp-qty' ?>">
                    <span><?= /* @noEscape */
                        $_item->getQty() * 1 ?></span>
                </div>
                <div class="<?= /** @noEscape */
                $a4Barcode ? 'mp-price-bc' : 'mp-price' ?>">
                    <?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
                        <?php if ($block->displayBothPrices()): ?>
                            <span class="label"><?= /* @noEscape */
                                __('Excl. Tax') ?>:</span>
                        <?php endif ?>
                        <?= /* @noEscape */
                        $_order->formatPrice($_item->getPrice()) ?>
                    <?php endif ?>

                    <?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
                        <?php if ($block->displayBothPrices()): ?>
                            <br/><span class="label"><?= /* @noEscape */
                                __('Incl. Tax') ?>:</span>
                        <?php endif ?>
                        <?= /* @noEscape */
                        $_order->formatPrice($_item->getPriceInclTax()) ?>
                    <?php endif ?>
                </div>
                <div class="<?= /** @noEscape */
                $a4Barcode ? 'mp-subtotal-bc' : 'mp-subtotal' ?>">
                    <?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
                        <?php if ($block->displayBothPrices()): ?>
                            <span class="label"><?= /* @noEscape */
                                __('Excl. Tax') ?>:</span>
                        <?php endif ?>
                        <?= /* @noEscape */
                        $_order->formatPrice($_item->getRowTotal()) ?>
                    <?php endif ?>

                    <?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
                        <?php if ($block->displayBothPrices()): ?>
                            <br/><span class="label"><?= /* @noEscape */
                                __('Incl. Tax') ?>:</span>
                        <?php endif ?>
                        <?php $_incl = $this->helper('Magento\Checkout\Helper\Data')->getSubtotalInclTax($_item) ?>
                        <?= /* @noEscape */
                        $_order->formatPrice($_incl) ?>
                    <?php endif ?>
                </div>
            </div>
            <div class="clr"></div>
        <?php endforeach ?>
    </div>
    <div class="order-totals">
        <?= $block->getChildHtml('invoice_totals') ?>
    </div>
<?php endif ?>
