FROM gitlab.hostplus.nl:5050/tropical-reefs/docker/php8.1:latest

# copy code
COPY . /var/www/html

# change ownership
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 775 /var/www/html/magento/var/
