before_script:
  - docker info

build:
  stage: build
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker buildx build -t --build-context othersource=../ $CI_REGISTRY_IMAGE/magento-php ./docker/php
    - docker push $CI_REGISTRY_IMAGE/magento-php
    - docker buildx build -t --build-context othersource=../ -t $CI_REGISTRY_IMAGE/magento ./docker/nginx
    - docker push $CI_REGISTRY_IMAGE/magento
