stages:
  - build_php
  - build_nginx

build_php:
    stage: build_php
    image:
      name: gcr.io/kaniko-project/executor:v1.9.0-debug
      entrypoint: [ "" ]
    only:
      - master
    script:
      - /kaniko/executor
        --context "${CI_PROJECT_DIR}"
        --dockerfile "${CI_PROJECT_DIR}/docker/php/Dockerfile"
        --destination "${CI_REGISTRY_IMAGE}/magento-php:${CI_COMMIT_TAG}"

build_nginx:
  stage: build_nginx
  when: on_success
  dependencies:
    - build_php
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/nginx/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/magento-nginx:${CI_COMMIT_TAG}"
