build:
    stage: build
    image:
      name: gcr.io/kaniko-project/executor:v1.9.0-debug
      entrypoint: [ "" ]
    only:
      - master
    script:
      - /kaniko/executor
        --context "${CI_PROJECT_DIR}"
        --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
        --destination "${CI_REGISTRY_IMAGE}/magento:${CI_COMMIT_TAG}"
    before_script:
        - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
        - echo $COMPOSER_AUTH >> auth.json
