<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>

<?php
$parentItem = $block->getItem();
$type = $block->getType();
$items = $block->getChildren($parentItem);
$_index = 0;
$_order = $block->getOrder();
$block->setStoreId($_order->getStoreId());
$isBarcode = $block->getIsBarcode();
$pageSize = $block->getPageSize();
$a4Barcode = $isBarcode && ($pageSize === 'A4');
$a5Barcode = $isBarcode && ($pageSize === 'A5');
$_store = $_order->getStore();
$_imageHelper = $block->getHelperImage();
$_messageHelper = $block->getHelperMessage();
$_baseImageUrl = $_store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'catalog/product';
$isMessageEnable = $_messageHelper->isMessagesAllowed('order_item', $parentItem) && $parentItem->getGiftMessageId();
?>

<?php if ($isMessageEnable || $block->getItemOptions() || $parentItem->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif ?>

<?php $_prevOptionId = '' ?>
<div class="bundle-item <?= /** @noEscape */ $block->getIndexKey() ?>" style="border-bottom: 1px solid #ddd;">
    <?php foreach ($items

    as $_item): ?>
    <?php
    // As part of invoice item renderer logic, the order is set on each invoice item.
    // In the case of a bundle product, this template takes over rendering its children,
    // so it is necessary to pass the order along to each child.
    $_item->setOrder($_order);
    ?>
    <div class="mp-row">
        <div class="mp-image">
            <img src="<?= $_imageHelper->init($_item->getOrderItem()->getProduct(), 'small_image',
                ['type'=>'small_image'])->keepAspectRatio(true)->resize('65','65')->getUrl();?>"
                 alt="<?= __('Product Image');?>">
        </div>
        <div class="<?= /** @noEscape */ $a4Barcode ? 'mp-item-bc' : 'mp-item' ?>">
            <?php if ($_item->getOrderItem()->getParentItem()): ?>
                <?php $attributes = $block->getSelectionAttributes($_item) ?>
                <?php if ($_prevOptionId != $attributes['option_id']): ?>
                    <div>
                        <strong><em><?= /* @noEscape */ $attributes['option_label'] ?></em></strong>
                    </div>
                    <?php $_prevOptionId = $attributes['option_id'] ?>
                <?php endif ?>
            <?php endif ?>
            <?php if (!$_item->getOrderItem()->getParentItem()): ?>
            <div class="item-info">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                <p class="sku"><?= /* @noEscape */ __('SKU: %1', $block->escapeHtml($_item->getSku())) ?></p>
            </div>
        </div>
        <?php else: ?>
        <div class="item-info">
            <p><?= $block->getValueHtml($_item) ?></p>
            <?php if ($a5Barcode): ?>
                <p>
                    <barcode code="<?= /* @noEscape */ $block->escapeHtml($_item->getSku()) ?>" type="C39E" size="0.9" height="0.7"/>
                </p>
            <?php endif ?>
        </div>
    </div>
<?php if ($a4Barcode): ?>
    <div class="mp-barcode-bc">
        <p>
            <barcode code="<?= /* @noEscape */ $block->escapeHtml($_item->getSku()) ?>" type="C39E" size="0.5"/>
        </p>
    </div>
<?php endif ?>
    <div class="<?= /** @noEscape */ $a4Barcode ? 'mp-qty-bc' : 'mp-qty' ?>">
        <span><?= /* @noEscape */ $_item->getQty() * 1 ?></span>
    </div>
    <div class="<?= /** @noEscape */ $a4Barcode ? 'mp-price-bc' : 'mp-price' ?>">
        <?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
            <?php if ($block->displayBothPrices()): ?>
                <span class="label"><?= /* @noEscape */ __('Excl. Tax') ?>:</span>
            <?php endif ?>
            <?= /* @noEscape */ $_order->formatPrice($_item->getPrice()) ?>
        <?php endif ?>

        <?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
            <?php if ($block->displayBothPrices()) : ?>
                <br/><span class="label"><?= /* @noEscape */ __('Incl. Tax') ?>:</span>
            <?php endif ?>
            <?= /* @noEscape */ $_order->formatPrice($_item->getPriceInclTax()) ?>
        <?php endif ?>
    </div>
    <div class="<?= /** @noEscape */ $a4Barcode ? 'mp-subtotal-bc' : 'mp-subtotal' ?>">
        <?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
            <?php if ($block->displayBothPrices()): ?>
                <span class="label"><?= /* @noEscape */ __('Excl. Tax') ?>:</span>
            <?php endif ?>
            <?= /* @noEscape */ $_order->formatPrice($_item->getRowTotal()) ?>
        <?php endif ?>

        <?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
            <?php if ($block->displayBothPrices()): ?>
                <br/><span class="label"><?= /* @noEscape */ __('Incl. Tax') ?>:</span>
            <?php endif ?>
            <?php $_incl = $this->helper(\Magento\Checkout\Helper\Data::class)->getSubtotalInclTax($_item) ?>
            <?= /* @noEscape */ $_order->formatPrice($_incl) ?>
        <?php endif ?>
    </div>
<?php endif ?>
</div>
    <div class="clr"></div>
<?php endforeach ?>

<?php if ($_showlastRow): ?>
    <div class="mp-row">
        <div class="item-extra">
            <?php if ($block->getItemOptions()): ?>
                <div>
                    <?php foreach ($block->getItemOptions() as $option): ?>
                        <div><strong><em><?= /* @noEscape */ $option['label'] ?></em></strong></div>
                        <div><?= /* @noEscape */ $option['value'] ?></div>
                    <?php endforeach ?>
                </div>
            <?php endif ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </div>
    </div>
<?php endif ?>
</div>
<div class="clr"></div>

